name: New Version Trigger Docs

on:
  push:

jobs:
  trigger-docs-build:
    runs-on: ubuntu-latest
    steps:
      - name: New version pushed
        # if: github.event.action != 'pong'
        run: |
          curl -X POST https://api.github.com/repos/Tokimon/jsfns-docs/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.ACCESS_TOKEN }} \
          --data '{"event_type": "new-version", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'
