name: New Version Trigger Docs
run-name: New version pushed

on:
  workflow_dispatch:
  create:
    tag:

jobs:
  trigger-docs-build:
    runs-on: ubuntu-latest
    steps:
      - name: what action
        run: |
          echo "Event '${{ github.event.action }}'"
      - name: New version pushed
        run: |
          curl --location 'https://api.github.com/repos/Tokimon/jsfns-docs/dispatches' \
          --header 'Accept: application/json' \
          --header 'Authorization: Bearer ${{ secrets.TROGELS }}' \
          --header 'Content-Type: application/json' \
          --data '{ "event_type": "new-version", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }'
