name: New Version Trigger Docs
run-name: New version pushed

on:
  workflow_dispatch:
  create: tag

jobs:
  trigger-docs-build:
    runs-on: ubuntu-latest
    steps:
      - name: Triggering Docs Build
        run: |
          curl --location 'https://api.github.com/repos/Tokimon/jsfns-docs/dispatches' \
          --header 'Accept: application/json' \
          --header 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'Content-Type: application/json' \
          --data '{ "event_type": "new-version"'
